<?php

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 */
 
function forget_password_error_text_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_pass') {
    unset($form['#validate']);
    $form['#validate'][] = 'resetPasswordValidate';
  }
}

function resetPasswordValidate(&$form, FormStateInterface $form_state) {
    $name = trim($form_state->getValue('name'));
    // Try to load by email.
    $users = \Drupal::entityTypeManager()->getStorage('user')
		->loadByProperties(['mail' => $name]);
    if (empty($users)) {
      // No success, try to load by name.
      $users = \Drupal::entityTypeManager()->getStorage('user')
		->loadByProperties(['name' => $name]);
    }
    $account = reset($users);
    if ($account && $account->id()) {
      // Blocked accounts cannot request a new password.
      if (!$account->isActive()) {
        $form_state->setErrorByName('name', t('%name is blocked or has not been activated yet.', ['%name' => $name]));
      }
      else {
        $form_state->setValueForElement(['#parents' => ['account']], $account);
      }
    }
    else {
      $form_state->setErrorByName('name', t('An error has occurred. If you do not receive an email in the next 30 minutes, please try again.', ['%name' => $name]));
	}
  }
 

 